HYPERLANE_AGENT_IMAGE = "gcr.io/abacus-labs-dev/hyperlane-agent:9612623-20230829-154513"

CONFIG_FILE_FOLDER = "/config/"
CONFIG_FILE_NAME = "agent_config.json"

DB_FOLDER = "/data/"

DEFAULT_ORIGIN_CHAIN_URL = "HYP_BASE_CHAINS_%s_CONNECTION_URL"
